# Generated by Django 4.2.11 on 2026-04-25 16:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Profil')),
                ('tipe_akun', models.CharField(choices=[('gmail', 'Gmail OAuth'), ('pens', 'Akun PENS'), ('umum', 'Pengguna Umum')], default='umum', max_length=10, verbose_name='Tipe Akun')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Terverifikasi')),
                ('tanggal_daftar', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Daftar')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Login Terakhir')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'db_table': 'auth_user_edutask',
                'ordering': ['-tanggal_daftar'],
            },
        ),
    ]
