# Generated by Django 4.2.11 on 2026-05-10 12:47

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    User.objects.filter(tipe_akun='pens').update(role='mahasiswa')
    User.objects.exclude(tipe_akun='pens').filter(role='umum').update(role='umum')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mata_kuliah',
            field=models.CharField(blank=True, max_length=120, verbose_name='Mata Kuliah Dosen'),
        ),
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='user',
            name='nrp',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NRP / NIM'),
        ),
        migrations.AddField(
            model_name='user',
            name='prodi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Program Studi'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('umum', 'Umum')], default='umum', max_length=12, verbose_name='Role'),
        ),
        migrations.RunPython(backfill_roles, migrations.RunPython.noop),
    ]
