# Generated by Django 4.2.11 on 2026-05-22 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_mata_kuliah_user_nip_user_nrp_user_prodi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama Kelas')),
                ('tingkat', models.PositiveIntegerField(verbose_name='Tingkat / Tahun')),
                ('prodi', models.CharField(max_length=100, verbose_name='Program Studi')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'db_table': 'kelas',
                'ordering': ['tingkat', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_list', to='authentication.kelas', verbose_name='Kelas Mahasiswa'),
        ),
    ]
