# Generated by Django 4.2.11 on 2026-05-23 04:37

import apps.authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_kelas_user_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuangEdukasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_join', models.CharField(default=apps.authentication.models.generate_join_code, max_length=10, unique=True)),
                ('nama_ruang', models.CharField(max_length=100, verbose_name='Nama Ruang')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anggota', models.ManyToManyField(blank=True, related_name='ruang_diikuti', to=settings.AUTH_USER_MODEL)),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruang_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruang Edukasi',
                'verbose_name_plural': 'Ruang Edukasi',
                'db_table': 'ruang_edukasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
