# Generated by Django 4.2.11 on 2026-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangedukasi',
            name='hari',
            field=models.IntegerField(blank=True, choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (0, 'Minggu')], null=True, verbose_name='Hari Kuliah'),
        ),
        migrations.AddField(
            model_name='ruangedukasi',
            name='jam_mulai',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Mulai'),
        ),
        migrations.AddField(
            model_name='ruangedukasi',
            name='jam_selesai',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Selesai'),
        ),
        migrations.AddField(
            model_name='ruangedukasi',
            name='ruangan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ruangan / Link Zoom'),
        ),
        migrations.AddField(
            model_name='ruangedukasi',
            name='warna',
            field=models.CharField(default='#8B6914', max_length=7, verbose_name='Warna (hex)'),
        ),
    ]
