# Generated by Django 4.2.20 on 2026-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_ruangedukasi_hari_ruangedukasi_jam_mulai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangedukasi',
            name='is_workspace',
            field=models.BooleanField(default=False, verbose_name='Apakah Workspace Proyek?'),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Kode Chat'),
        ),
    ]
