# Generated by Django 4.2.20 on 2026-06-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_ruangedukasi_is_workspace_user_chat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nrp',
        ),
    ]
