# Generated by Django 4.2.20 on 2026-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_populate_chat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_profil',
        ),
    ]
