# Generated by Django 4.2.11 on 2026-05-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKuliah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=10)),
                ('jam', models.CharField(help_text='Contoh: 08:00-10:00', max_length=30)),
                ('ruangan', models.CharField(max_length=80)),
                ('dosen', models.CharField(max_length=100)),
                ('mata_kuliah', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kuliah', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jadwal_kuliah',
                'ordering': ['hari', 'jam', 'mata_kuliah'],
            },
        ),
    ]
