# Generated by Django 4.2.11 on 2026-04-25 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Mata Kuliah')),
                ('nama_dosen', models.CharField(blank=True, max_length=100, verbose_name='Nama Dosen')),
                ('warna', models.CharField(default='#8B6914', max_length=7, verbose_name='Warna (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mata Kuliah',
                'verbose_name_plural': 'Mata Kuliah',
                'db_table': 'mata_kuliah',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Task')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('prioritas', models.CharField(choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], default='sedang', max_length=10, verbose_name='Prioritas')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=15, verbose_name='Status')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mata_kuliah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.matakuliah', verbose_name='Mata Kuliah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
                'ordering': ['urutan', 'deadline', '-created_at'],
            },
        ),
    ]
