# Generated by Django 4.2.11 on 2026-05-22 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_kelas_user_kelas'),
        ('tasks', '0002_alter_matakuliah_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenugasanDosen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mata_kuliah', models.CharField(max_length=120, verbose_name='Mata Kuliah')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Tugas')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('prioritas', models.CharField(choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], default='sedang', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penugasan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kelas_tujuan', models.ManyToManyField(related_name='penugasan_diterima', to='authentication.kelas')),
            ],
            options={
                'verbose_name': 'Penugasan Dosen',
                'verbose_name_plural': 'Penugasan Dosen',
                'db_table': 'penugasan_dosen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='source_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributed_tasks', to='tasks.penugasandosen', verbose_name='Sumber Penugasan Dosen'),
        ),
    ]
