# Generated by Django 4.2.11 on 2026-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_penugasandosen_task_source_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penugasandosen',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
