# Generated by Django 4.2.11 on 2026-05-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_penugasandosen_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penugasandosen',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
