# Generated by Django 4.2.11 on 2026-05-23 04:02

import apps.tasks.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_attachment_taskcomment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='hari',
            field=models.IntegerField(blank=True, choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (0, 'Minggu')], null=True, verbose_name='Hari Kuliah'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='jam_mulai',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Mulai'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='jam_selesai',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Selesai'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='ruangan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ruangan / Link Zoom'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip', 'png', 'jpg', 'jpeg', 'xls', 'xlsx']), apps.tasks.models.validate_file_size], verbose_name='Lampiran Berkas'),
        ),
    ]
