# Generated by Django 4.2.11 on 2026-05-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_ruangedukasi'),
        ('tasks', '0007_matakuliah_hari_matakuliah_jam_mulai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penugasandosen',
            name='kelas_tujuan',
        ),
        migrations.AddField(
            model_name='penugasandosen',
            name='ruang_tujuan',
            field=models.ManyToManyField(related_name='penugasan_diterima', to='authentication.ruangedukasi'),
        ),
    ]
