# Generated by Django 4.2.20 on 2026-06-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_ruangedukasi_is_workspace_user_chat_code'),
        ('tasks', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_tasks', to='authentication.ruangedukasi', verbose_name='Workspace Kolaborasi'),
        ),
    ]
